Metrics/LineLength:
  Max: 90

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Guardfile'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    
Lint/NestedMethodDefinition:
  Exclude:
    - 'app/controllers/concerns/**/*'  
    
Metrics/AbcSize:
  Exclude:
    - 'app/controllers/concerns/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/**/*'
    - 'app/my/**/*'
    - 'app/controllers/concerns/**/*'
    
Metrics/ClassLength:
  Exclude:
    - 'app/models/user.rb'
    
Metrics/AbcSize:
  Exclude:
    - 'app/controllers/concerns/**/*'
    
Metrics/ModuleLength:
  Exclude:
    - 'app/controllers/concerns/**/*'
    
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/policies/**/*'
    