version: 0.2

phases:
  install:
    runtime-versions:
        ruby: 2.6
    commands:
      # - echo Starting postgresql...
      # - service postgresql start
      - echo Installing Bundler...
      - gem install bundler
      - bundle install --with test
  pre_build:
    commands:
      - echo Preparing database to run tests...\
      - RAILS_ENV=stage bundle exec rake db:setup
      - RAILS_ENV=stage bundle exec rake db:migrate
  build:
    commands:
      - echo Running rspec tests...
      - bundle exec rspec spec/