##
# Allow more secure way of handling credentials as environmental variables
#
# $ echo "export USERNAME=username" >> ~/.profile
#
# $ echo "export PASSWORD=password" >> ~/.profile

# database.yml
default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: <%= ENV['USER_NAME'] %>
      password: <%= ENV['PASSWORD'] %>
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  # database: <%= ENV['RDS_DB_NAME'] %>
  # username: <%= ENV['RDS_USERNAME'] %>
  # password: <%= ENV['RDS_PASSWORD'] %>
  # host: <%= ENV['RDS_HOSTNAME'] %>
  # port: <%= ENV['RDS_PORT'] %>
  
staging:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>