default:
  web_object:
    api_key: <%= ENV['API_KEY'] %>
    weight: 1000000
  
  
account:
  grace_period: 30      # days
  price_per_level:
    1: 200
    3: 550
    6: 1000
    12: 1900
  max_weight_per_level: 100
  