# frozen_string_literal: true

# Base controller generated by Rails
class ApplicationController < ActionController::Base
  include Pundit
  include ExceptionHandler
  include ResponseHandler

  # after_action :verify_authorized, unless: :active_admin_controller?
  # after_action :verify_authorized

  def policy(record)
    policies[record] ||=
      "#{controller_path.classify}Policy".constantize.new(pundit_user, record)
  end

  def authenticate_admin_user!
    if user_signed_in? && !current_user.can_be_manager?
      redirect_to(
        root_path
      ) && return
    end
    redirect_to new_user_session_path unless authenticate_user!
  end
end
