# frozen_string_literal: true

# Base controller generated by Rails
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  # after_action :verify_authorized, unless: :active_admin_controller?
  after_action :verify_authorized

  def policy(record)
    policies[record] ||=
      "#{controller_path.classify}Policy".constantize.new(pundit_user, record)
  end
end
